name: Build & test

on:
  pull_request:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - name: Build & Typecheck
      run: npm run build
    - name: Lint
      run: npm run lint
